#!/bin/sh
# Add this to the bashrc so you can run this script in any directory:
# export PATH=$PATH:~/Documents/ardupilot_gazebo/scripts/SITLInterface/



echo "Launching Ardupilot SITL"

gnome-terminal --tab -e "bash -c \"python ~/Documents/ardupilot_beta/Tools/autotest/sim_vehicle.py -v ArduCopter -f gazebo-iris --console; exec bash\""

echo "Running Joystick SITL interface"
# gnome-terminal -e "bash -c \"!!; exec bash\"" to run commands in a new terminal
# Just relace the !!
# Found here: https://askubuntu.com/questions/484993/run-command-on-anothernew-terminal-window
gnome-terminal --tab --working-directory=Documents/ardupilot_gazebo/scripts/SITLInterface -e "bash -c \"python sitl_interface.py; exec bash\""


# Launch Gazebo with user arguments
echo "Running Desired World: $1"
if [ "$1" = "cam_rail" ]
    then 
        gazebo --verbose iris_irlock_rail_sim.world
elif [ "$1" = "nocam_rail" ]
    then gazebo --verbose iris_irlock_nocam_rail_sim.world
elif [ "$1" = "cam_no_rail" ]
    then gazebo --verbose iris_irlock_demo.world
fi